<Project>
    <PropertyGroup Condition="Exists('$(EngineDir)/Build/Build.version')">
        <UEBuildVersion>$([System.IO.File]::ReadAllText('$(EngineDir)/Build/Build.version'))</UEBuildVersion>
        <UEBuildMajorVersion>$([System.Text.RegularExpressions.Regex]::Match($(UEBuildVersion), '&quot;MajorVersion&quot;\s*:\s*(\d+)').Groups[1].Value)</UEBuildMajorVersion>
        <UEBuildMinorVersion>$([System.Text.RegularExpressions.Regex]::Match($(UEBuildVersion), '&quot;MinorVersion&quot;\s*:\s*(\d+)').Groups[1].Value)</UEBuildMinorVersion>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <TargetFramework Condition="'$(UEBuildMajorVersion)' != '' and '$(UEBuildMinorVersion)' != '' and ($(UEBuildMajorVersion) &gt; 5 or ($(UEBuildMajorVersion) == 5 and $(UEBuildMinorVersion) &gt;= 8))">net10.0</TargetFramework>
    </PropertyGroup>
</Project>
